// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi-T4MJcWsynpyZLVNZsbg_4QYSgGP6yI',
    appId: '1:646960964581:web:bc89e481523b579fd1c50c',
    messagingSenderId: '646960964581',
    projectId: 'jahizzz',
    authDomain: 'jahizzz.firebaseapp.com',
    storageBucket: 'jahizzz.firebasestorage.app',
    measurementId: 'G-F9J19BXK4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5VUsI7GUKLMLMq8LJG8lbcZbGygGcih0',
    appId: '1:646960964581:android:0dd433c865df43bfd1c50c',
    messagingSenderId: '646960964581',
    projectId: 'jahizzz',
    storageBucket: 'jahizzz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAu0tTSTEBe_ElI5a0K6TrPRh6cp6_ycU',
    appId: '1:646960964581:ios:0d7b4369880b94c0d1c50c',
    messagingSenderId: '646960964581',
    projectId: 'jahizzz',
    storageBucket: 'jahizzz.firebasestorage.app',
    iosBundleId: 'com.example.jahiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAu0tTSTEBe_ElI5a0K6TrPRh6cp6_ycU',
    appId: '1:646960964581:ios:0d7b4369880b94c0d1c50c',
    messagingSenderId: '646960964581',
    projectId: 'jahizzz',
    storageBucket: 'jahizzz.firebasestorage.app',
    iosBundleId: 'com.example.jahiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi-T4MJcWsynpyZLVNZsbg_4QYSgGP6yI',
    appId: '1:646960964581:web:fc354ecc3f70c645d1c50c',
    messagingSenderId: '646960964581',
    projectId: 'jahizzz',
    authDomain: 'jahizzz.firebaseapp.com',
    storageBucket: 'jahizzz.firebasestorage.app',
    measurementId: 'G-6N9925SGJ1',
  );
}
